name: build upload deploy

on:
  push:
    branches: ["master"]
  
jobs:
  dockerize: 
    name: push to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: xsharawi/chattingapp
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: xsharawi/chattingapp:latestDOCKER_TOKEN
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa $EC2_IP >> ~/.ssh/known_hosts
      - name: SSH into the remote machine
        run: |
          ssh -i ~/.ssh/id_rsa user@$EC2_IP 
          sudo docker stop app
          sudo docker remove app
          sleep 3
          sudo docker pull xsharawi/chattingapp
          sudo docker run xsharawi/chattingapp
